params:
   author: "Baron Schwartz"
   Tagline: "Stay Curious!"
   Title: "Xaprb"
   ga_account: "0xdeadbeef"
   domain: "xaprb.com"
   DateForm: "Mon, Jan 2, 2006"
   RecentLimit: 20
   DisqusUser: "xaprb"
   BaseUrl: 'http://www.xaprb.com/'
   LanyonOptions: "layout-reverse sidebar-overlay"
Taxonomies:
   category: "categories"
---
